[workspace]
resolver = "2"
members = [
    "profusion", "profusion-macros", "profusion-tests"
]

[profile.release]
opt-level = 3
lto = true

[profile.test]
opt-level = 0
codegen-units = 1
lto = false
