[package]
name = "profusion"
version = "0.1.0"
authors = ["Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>"]
edition = "2018"
repository = "https://github.com/EcomDev/profusion-rs"
license = "MIT"

[lib]
name = "profusion"
crate-type = [ "lib" ]

[dependencies.tokio]
version = "1.6"
features = [ "rt", "time", "macros" ]

[dependencies.futures]
version = "0.3"

[features]
test = []
